-- 30 additional sample alumni. Safe to re-run (guarded by NOT EXISTS on email).
-- Shares the same sample password as every other seeded alumni: ChangeMe@123.
-- Run against an already-selected database (phpMyAdmin) or on the command line
-- as `mysql ... your_db_name < seed_alumni_batch2.sql` - no USE/CREATE DATABASE
-- here, since most hosts don't grant the app's DB user that permission.

SET @pw := (SELECT password_hash FROM users WHERE email = 'chidi.okonkwo@example.com' LIMIT 1);

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Yewande Adisa','yewande.adisa@example.com',@pw,'Head of Credit Risk, Access Bank','Access Bank','Banking & Finance','Lagos','Nigeria',2017,'MBA','Leading credit risk strategy across Access Bank''s retail lending portfolio.','Credit Risk, Portfolio Management, Basel III','Risk Management','Digital Lending','https://linkedin.com/in/yewandeadisa','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='yewande.adisa@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility, is_mentor, mentorship_areas)
SELECT 'alumni','Kelechi Nnamdi','kelechi.nnamdi@example.com',@pw,'VP Engineering, Kuda Bank','Kuda Bank','Technology & Fintech','Lagos','Nigeria',2016,'Executive MBA','Building the engineering culture behind one of Nigeria''s fastest-growing digital banks.','Engineering Leadership, Cloud Architecture, Fintech','Digital Banking','Neobanking','https://linkedin.com/in/kelechinnamdi','active','public',1,'Engineering Careers, Fintech' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='kelechi.nnamdi@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Aisha Mohammed','aisha.mohammed@example.com',@pw,'Regional HR Director, Nigerian Breweries','Nigerian Breweries','Consumer Goods','Kaduna','Nigeria',2015,'MBA','Overseeing talent strategy across Nigerian Breweries'' northern operations.','HR Strategy, Talent Development, Change Management','People Operations','FMCG','https://linkedin.com/in/aishamohammed','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='aisha.mohammed@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility, is_mentor, mentorship_areas)
SELECT 'alumni','Femi Adewale','femi.adewale@example.com',@pw,'Managing Director, Renmoney','Renmoney','Banking & Finance','Lagos','Nigeria',2013,'Executive MBA','Leading digital lending operations serving underbanked Nigerian consumers and SMEs.','Consumer Lending, P&L Management, Strategy','Digital Lending','Financial Inclusion','https://linkedin.com/in/femiadewale','active','public',1,'Executive Leadership, Fintech Strategy' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='femi.adewale@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Ngozi Obiora','ngozi.obiora@example.com',@pw,'Supply Chain Manager, Lafarge Africa','Lafarge Africa','Manufacturing','Ibadan','Nigeria',2019,'MBA','Optimizing cement production supply chains across South-West Nigeria.','Supply Chain, Logistics, Procurement','Manufacturing Operations','Industrial Manufacturing','https://linkedin.com/in/ngoziobiora','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='ngozi.obiora@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Babajide Fashola','babajide.fashola@example.com',@pw,'Head of Underwriting, AXA Mansard Insurance','AXA Mansard Insurance','Insurance','Lagos','Nigeria',2014,'MSc Finance','Managing underwriting strategy for corporate and retail insurance lines.','Underwriting, Actuarial Analysis, Risk Assessment','Insurance','InsurTech','https://linkedin.com/in/babajidefashola','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='babajide.fashola@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility, is_mentor, mentorship_areas)
SELECT 'alumni','Chidinma Uzo','chidinma.uzo@example.com',@pw,'Founder, Uzo Wellness Clinics','Uzo Wellness Clinics','Healthcare','Enugu','Nigeria',2018,'MBA','Building a chain of affordable primary healthcare clinics across South-East Nigeria.','Healthcare Management, Entrepreneurship, Operations','Healthcare Delivery','Primary Healthcare','https://linkedin.com/in/chidinmauzo','active','public',1,'Healthcare Entrepreneurship' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='chidinma.uzo@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Suleiman Bello','suleiman.bello@example.com',@pw,'Country Manager, Seplat Energy','Seplat Energy','Oil & Gas','Port Harcourt','Nigeria',2011,'Executive MBA','Leading upstream operations for one of Nigeria''s largest independent energy companies.','Energy Operations, Regulatory Affairs, Strategy','Oil & Gas','Energy Transition','https://linkedin.com/in/suleimanbello','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='suleiman.bello@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Temitope Adeyemi','temitope.adeyemi@example.com',@pw,'Product Lead, Cowrywise','Cowrywise','Technology & Fintech','Lagos','Nigeria',2020,'MBA','Building savings and investment products for young African professionals.','Product Management, Fintech, UX Strategy','Wealth Tech','Personal Finance','https://linkedin.com/in/temitopeadeyemi','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='temitope.adeyemi@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Ikechukwu Okoro','ikechukwu.okoro@example.com',@pw,'Finance Director, Cadbury Nigeria','Cadbury Nigeria','Consumer Goods','Lagos','Nigeria',2012,'Executive MBA','Overseeing financial strategy and reporting for Cadbury''s Nigerian operations.','Financial Reporting, Corporate Finance, Budgeting','FMCG Finance','Consumer Goods','https://linkedin.com/in/ikechukwuokoro','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='ikechukwu.okoro@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility, is_mentor, mentorship_areas)
SELECT 'alumni','Zainab Yusuf','zainab.yusuf@example.com',@pw,'Senior Legal Counsel, First Bank Nigeria','First Bank Nigeria','Banking & Finance','Abuja','Nigeria',2016,'MBA','Advising on regulatory compliance and corporate transactions for one of Nigeria''s oldest banks.','Banking Law, Compliance, Contract Negotiation','Financial Regulation','Corporate Governance','https://linkedin.com/in/zainabyusuf','active','public',1,'Legal Careers, Banking Compliance' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='zainab.yusuf@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Olumide Fagbenle','olumide.fagbenle@example.com',@pw,'Director of Operations, MainOne','MainOne','Technology & Fintech','Lagos','Nigeria',2015,'Executive MBA','Leading data infrastructure operations across West Africa''s largest connectivity provider.','Infrastructure Operations, Telecom, Data Centers','Digital Infrastructure','Connectivity','https://linkedin.com/in/olumidefagbenle','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='olumide.fagbenle@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Chizoba Nwachukwu','chizoba.nwachukwu@example.com',@pw,'Brand Manager, Unilever Nigeria','Unilever Nigeria','Consumer Goods','Lagos','Nigeria',2021,'MSc Marketing','Managing personal care brand strategy across Nigeria and Ghana.','Brand Management, Consumer Insights, Campaign Strategy','FMCG Marketing','Personal Care','https://linkedin.com/in/chizobanwachukwu','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='chizoba.nwachukwu@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Hauwa Garba','hauwa.garba@example.com',@pw,'Regional Sales Director, Coca-Cola Nigeria','Coca-Cola Nigeria','Consumer Goods','Kano','Nigeria',2014,'Executive MBA','Driving distribution and sales growth across Northern Nigeria''s beverage market.','Sales Strategy, Distribution, Key Account Management','Beverage Industry','FMCG','https://linkedin.com/in/hauwagarba','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='hauwa.garba@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Emmanuel Etuk','emmanuel.etuk@example.com',@pw,'Actuarial Analyst, Fidelity Bank','Fidelity Bank','Banking & Finance','Uyo','Nigeria',2022,'MSc Finance','Building risk models for retail and SME lending portfolios.','Actuarial Science, Data Analysis, Risk Modelling','Retail Banking','Data Science','https://linkedin.com/in/emmanueletuk','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='emmanuel.etuk@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility, is_mentor, mentorship_areas)
SELECT 'alumni','Fatima Sani','fatima.sani@example.com',@pw,'Co-Founder, Sani Agro Exports','Sani Agro Exports','Agriculture & Agribusiness','Kano','Nigeria',2017,'MBA','Exporting processed agricultural produce from Northern Nigeria to European markets.','Agribusiness, Export Trade, Supply Chain','Agriculture','Agri-exports','https://linkedin.com/in/fatimasani','active','public',1,'Agribusiness, Export Trade' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='fatima.sani@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Adebayo Ogunleye','adebayo.ogunleye@example.com',@pw,'Head of Digital Banking, Wema Bank','Wema Bank','Banking & Finance','Lagos','Nigeria',2013,'Executive MBA','Leading ALAT, Wema Bank''s fully digital banking arm.','Digital Banking, Product Strategy, Innovation','Digital Transformation','Neobanking','https://linkedin.com/in/adebayoogunleye','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='adebayo.ogunleye@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Nkechi Chukwuemeka','nkechi.chukwuemeka@example.com',@pw,'Real Estate Development Manager, UPDC','UPDC','Real Estate','Lagos','Nigeria',2019,'MBA','Managing residential and commercial development projects across Lagos.','Real Estate Development, Project Management, Construction Finance','Property Development','Urban Development','https://linkedin.com/in/nkechichukwuemeka','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='nkechi.chukwuemeka@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Rasheed Balogun','rasheed.balogun@example.com',@pw,'Operations Manager, Providus Bank','Providus Bank','Banking & Finance','Lagos','Nigeria',2020,'MBA','Streamlining branch and back-office operations for a fast-growing commercial bank.','Operations Management, Process Improvement, Banking','Retail Banking','Process Optimization','https://linkedin.com/in/rasheedbalogun','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='rasheed.balogun@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility, is_mentor, mentorship_areas)
SELECT 'alumni','Omolara Ajibade','omolara.ajibade@example.com',@pw,'Chief Marketing Officer, Konga','Konga','Technology & Fintech','Lagos','Nigeria',2015,'Executive MBA','Leading brand and growth marketing for one of Nigeria''s pioneering e-commerce platforms.','Growth Marketing, E-commerce, Brand Strategy','Retail Tech','E-commerce','https://linkedin.com/in/omolaraajibade','active','public',1,'Marketing Leadership, E-commerce' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='omolara.ajibade@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Chukwuemeka Eze','chukwuemeka.eze@example.com',@pw,'Plant Manager, Nigerian Breweries','Nigerian Breweries','Manufacturing','Enugu','Nigeria',2016,'Executive MBA','Overseeing brewery operations and production efficiency in South-East Nigeria.','Manufacturing Operations, Lean Manufacturing, Safety Management','Production Management','Beverage Manufacturing','https://linkedin.com/in/chukwuemekaeze','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='chukwuemeka.eze@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Amina Lawal','amina.lawal@example.com',@pw,'Investment Analyst, Union Bank Nigeria','Union Bank Nigeria','Banking & Finance','Abuja','Nigeria',2021,'MSc Finance','Evaluating investment opportunities across Union Bank''s corporate portfolio.','Investment Analysis, Financial Modelling, Valuation','Corporate Finance','Capital Markets','https://linkedin.com/in/aminalawal','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='amina.lawal@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Tunji Alabi','tunji.alabi@example.com',@pw,'Founder & CEO, Alabi Media Group','Alabi Media Group','Media & Entertainment','Lagos','Nigeria',2014,'MBA','Building a cross-platform media company spanning radio, digital and events.','Media Strategy, Content Production, Entrepreneurship','Media & Broadcasting','Digital Media','https://linkedin.com/in/tunjialabi','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='tunji.alabi@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility, is_mentor, mentorship_areas, is_spotlighted, spotlight_note)
SELECT 'alumni','Vivian Okonjo','vivian.okonjo@example.com',@pw,'Country Director, 54gene','54gene','Healthcare','Lagos','Nigeria',2013,'Executive MBA','Leading Nigerian operations for a genomics research company advancing precision medicine in Africa.','Healthcare Strategy, Genomics, Partnerships','Health Tech','Precision Medicine','https://linkedin.com/in/vivianokonjo','active','public',1,'Healthcare Innovation, Biotech',1,'Recognized for pioneering genomics research partnerships across West African hospitals.' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='vivian.okonjo@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Musa Danjuma','musa.danjuma@example.com',@pw,'Regional Manager, Total Energies','Total Energies','Energy','Kaduna','Nigeria',2012,'Executive MBA','Managing fuel retail operations across Northern Nigeria''s distribution network.','Retail Operations, Distribution, Energy','Downstream Energy','Fuel Retail','https://linkedin.com/in/musadanjuma','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='musa.danjuma@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Bisi Adeoye','bisi.adeoye@example.com',@pw,'Talent Acquisition Lead, Andela','Andela','Technology & Fintech','Lagos','Nigeria',2020,'MBA','Recruiting and placing top African engineering talent with global companies.','Talent Acquisition, HR Tech, Recruiting Strategy','Tech Talent','EdTech','https://linkedin.com/in/bisiadeoye','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='bisi.adeoye@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Chinedu Obi','chinedu.obi@example.com',@pw,'Compliance Manager, UBA','United Bank for Africa','Banking & Finance','Lagos','Nigeria',2018,'MBA','Ensuring regulatory compliance across UBA''s pan-African banking operations.','Regulatory Compliance, AML, Risk Management','Banking Compliance','Financial Crime Prevention','https://linkedin.com/in/chineduobi','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='chinedu.obi@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Rukayat Bakare','rukayat.bakare@example.com',@pw,'Product Designer, Carbon','Carbon','Technology & Fintech','Lagos','Nigeria',2022,'MBA','Designing digital lending and payments experiences for African consumers.','Product Design, UX Research, Fintech','Digital Lending','Consumer Fintech','https://linkedin.com/in/rukayatbakare','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='rukayat.bakare@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility)
SELECT 'alumni','Godwin Osei','godwin.osei@example.com',@pw,'Finance Manager, MTN Ghana','MTN Ghana','Telecommunications','Accra','Ghana',2016,'Executive MBA','Managing financial planning and analysis for MTN''s Ghanaian operations.','Financial Planning, Telecom Finance, Budgeting','Telecommunications','Mobile Money','https://linkedin.com/in/godwinosei','active','public' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='godwin.osei@example.com');

INSERT INTO users (role, name, email, password_hash, headline, company, industry, city, country, graduation_year, program, bio, skills, expertise_areas, business_interests, linkedin_url, status, profile_visibility, is_mentor, mentorship_areas)
SELECT 'alumni','Precious Mensah','precious.mensah@example.com',@pw,'Founder, Mensah Consulting Group','Mensah Consulting Group','Professional Services','Kumasi','Ghana',2015,'MBA','Advising SMEs across Ghana on strategy, operations and growth financing.','Management Consulting, SME Advisory, Strategy','Business Consulting','SME Growth','https://linkedin.com/in/preciousmensah','active','public',1,'Consulting Careers, SME Strategy' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='precious.mensah@example.com');
