-- Run against an already-selected database (phpMyAdmin) or on the command line
-- as `mysql ... your_db_name < seed_giving_causes.sql` - no USE/CREATE DATABASE
-- here, since most hosts don't grant the app's DB user that permission.

INSERT INTO giving_causes (column_group, slug, title, description, body, icon, sort_order) VALUES
('support','make-a-donation','Make a Donation','Contribute to initiatives that transform lives.','<p>Every gift, no matter the size, helps RBSN expand access to world-class business education. Unrestricted donations are directed to the areas of greatest need each academic year — from financial aid to campus resources.</p>','fa-solid fa-heart',1),
('support','scholarships','Scholarships','Support students through scholarships and bursaries.','<p>Scholarships open doors for talented students who could not otherwise afford an RBSN education. Your contribution can fund a full or partial scholarship and be named in honour of someone who inspired you.</p>','fa-solid fa-graduation-cap',2),
('support','academic-excellence','Academic Excellence','Fund faculty, research and academic programs.','<p>Support the recruitment of world-class faculty, curriculum innovation, and academic programming that keeps RBSN at the forefront of business education in Africa.</p>','fa-solid fa-building-columns',3),
('support','innovation-research','Innovation & Research','Drive innovation and research that matters.','<p>Fund faculty and student research addressing real business challenges across African markets, from fintech adoption to sustainable supply chains.</p>','fa-regular fa-lightbulb',4),
('support','student-development','Student Development','Empower student clubs, projects and competitions.','<p>Support student-led clubs, case competitions, and leadership development programs that build well-rounded, career-ready graduates.</p>','fa-solid fa-seedling',5),
('support','facilities-infrastructure','Facilities & Infrastructure','Help build world-class facilities.','<p>Contribute to campus facilities — classrooms, technology, and shared spaces — that shape the learning experience for generations of RBSN students.</p>','fa-solid fa-trophy',6),

('involve','volunteer','Volunteer','Share your time and expertise.','<p>Volunteer your time for career panels, admissions events, orientation programs, or alumni chapter activities. Every hour you give strengthens the RBSN community.</p>','fa-regular fa-hand',1),
('involve','guest-speaker','Guest Speaker','Share your insights and experiences.','<p>Guest speakers bring real-world perspective into the classroom. Share your career journey, industry expertise, or entrepreneurial story with current students.</p>','fa-solid fa-microphone',2),
('involve','industry-connect','Industry Connect','Create opportunities for students.','<p>Help connect RBSN students and graduates with opportunities at your organization — from site visits and case studies to hiring pipelines.</p>','fa-solid fa-handshake',3),
('involve','pro-bono-support','Pro Bono Support','Provide professional expertise for good.','<p>Offer pro bono consulting, legal, financial, or strategic support to student ventures and RBSN-affiliated social impact projects.</p>','fa-solid fa-scale-balanced',4),

('impact','start-a-fund','Start a Fund','Establish a fund for a cause you care about.','<p>Work with the Giving team to establish a dedicated fund — for scholarships, research, or a cause close to your heart — with terms you help define.</p>','fa-solid fa-hand-holding-dollar',1),
('impact','corporate-partnerships','Corporate Partnerships','Partner with the school to drive impact.','<p>Partner your organization with RBSN through sponsorships, joint research, recruiting partnerships, or co-branded executive education programs.</p>','fa-solid fa-building',2),
('impact','endow-a-chair','Endow a Chair','Support academic chairs and professorships.','<p>Endowing a faculty chair is one of the most enduring ways to shape RBSN''s academic future, attracting and retaining top scholars in a chosen field.</p>','fa-solid fa-chair',3),
('impact','leave-a-legacy','Leave a Legacy','Include the Business School in your estate plans.','<p>Planned gifts — bequests, trusts, and other estate commitments — ensure your impact on RBSN continues for generations to come.</p>','fa-solid fa-leaf',4),
('impact','giving-societies','Giving Societies','Join leadership giving societies.','<p>Join fellow alumni donors in RBSN''s leadership giving societies, recognizing sustained and significant contributions to the school''s mission.</p>','fa-solid fa-people-group',5),
('impact','impact-reports','Impact Reports','See how your support makes a difference.','<p>Explore how alumni giving has translated into scholarships awarded, research funded, and student lives changed over the past year.</p>','fa-solid fa-chart-column',6)
ON DUPLICATE KEY UPDATE title = VALUES(title);
